name: M3U with TikTok live GDrive 
# Δημιουργια M3U απο το σκριπτ generate_m3u.py και μετακινήση στο δημόσιο αποθετήριο και ανεβάσμα στο Google Drive
on:
  schedule:
    - cron: '0,30 * * * *' # Εκτελεί το workflow κάθε μισή ώρα
  workflow_dispatch: # Επιτρέπει την εκτέλεση του workflow χειροκίνητα από το GitHub UI

jobs:
  generate-m3u:
    runs-on: ubuntu-latest # Χρησιμοποιεί την τελευταία έκδοση του Ubuntu ως περιβάλλον εκτέλεσης

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Κάνει checkout το αποθετήριο ώστε να έχουμε πρόσβαση στον κώδικα

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Ρυθμίζει το περιβάλλον Python στην έκδοση 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip # Αναβάθμιση του pip
          pip install -r requirements.txt # Εγκατάσταση των εξαρτήσεων από το αρχείο requirements.txt

      - name: Run generate_m3u.py script
        run: |
          python generate_m3u.py # Εκτέλεση του σκριπτ generate_m3u.py

      - name: Display contents of current directory
        run: |
         ls -la # Εμφάνιση των περιεχομένων του τρέχοντος φακέλου

      - name: Install gdrive
        run: |
          curl -L -o gdrive https://github.com/prasmussen/gdrive/releases/download/2.1.0/gdrive-linux-x64 # Κατέβασμα του gdrive CLI εργαλείου
          chmod +x gdrive # Δίνουμε δικαιώματα εκτέλεσης στο gdrive
          sudo install gdrive /usr/local/bin/gdrive # Εγκατάσταση του gdrive στο σύστημα

      - name: Upload to Google Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }} # Το ID του φακέλου στο Google Drive
          GDRIVE_SECRET: ${{ secrets.GDRIVE_SECRET }} # Το JSON αρχείο των credentials
        run: |
          echo "${GDRIVE_SECRET}" > gdrive_secret.json # Αποθήκευση των credentials σε αρχείο
          gdrive upload --parent ${GDRIVE_FOLDER_ID} tiktok_live.m3u --service-account gdrive_secret.json # Ανέβασμα του αρχείου στο Google Drive
        run: |
          echo "${GDRIVE_SECRET}" > gdrive_secret.json
          gdrive upload --parent ${GDRIVE_FOLDER_ID} tiktok_live.m3u --service-account gdrive_secret.json # Ανέβασμα του αρχείου στο Google Drive
