name: Run TikTok Live Checker Script

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: # Προσθέτει τη δυνατότητα χειροκίνητης εκτέλεσης

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Streamlink
      run: sudo apt-get update && sudo apt-get install -y streamlink

    - name: Run script
      run: python check_tiktok_live.py
