name: Run TikTok Live Checker Python Script and Update M3U

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Streamlink
      run: sudo apt-get update && sudo apt-get install -y streamlink

    - name: Run Python script
      run: |
        python check_tiktok_live.py
      continue-on-error: false

    - name: Display M3U file content
      run: cat tiktok_live.m3u

    - name: Commit and push M3U file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add tiktok_live.m3u
        git commit -m 'Update M3U file'
        git push
