name: Schedule TikTok Live Check

on: 
  schedule: 
    - cron: "0 * * * *"  # Εκτέλεση κάθε ώρα στις :00 
    - cron: "30 * * * *"  # Εκτέλεση κάθε ώρα στις :30
  push:
    branches:
      - main

jobs:  
  build:    
    runs-on: ubuntu-latest    

    steps:      
      - name: Check out the repository        
        uses: actions/checkout@v3

      - name: Set up Python        
        uses: actions/setup-python@v3        
        with:          
          python-version: 3.x

      - name: Install dependencies        
        run: |          
          python -m pip install --upgrade pip          
          pip install -r requirements.txt

      - name: Run the script        
        run: python check_tiktok_live.py

      - name: Commit and push changes
        run: |
          git config --global user.email "Blueddo@users.noreply.github.com"
          git config --global user.name "Blueddo"
          git add tiktok_live.m3u
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update tiktok_live.m3u"
            git push https://Blueddo:${{ secrets.ACTIONS_PAT }}@github.com/Blueddo/tiktok-live-script.git
          else
            echo "No changes to commit."
          fi
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
