name: Schedule TikTok Live Check

on:
  schedule:
    - cron: "0 * * * *"  # Εκτέλεση κάθε ώρα στις :00
    - cron: "30 * * * *"  # Εκτέλεση κάθε ώρα στις :30

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python check_tiktok_live.py
